### PR TITLE
update to 2021.04.0

### PR DESCRIPTION
**Pull request by katietz**

### CODE REVIEW

**Comment by katietz** [comment]
built for all intel architectures see https://concourse.build.corp.continuum.io/teams/main/pipelines/ktietz_t4

**Review by antkneed — APPROVED** [review]
👍

**Comment by skupr-anaconda** [comment]
Are logs correct for `daal` and `daal-include` - **0 files**?:
```
Packaging daal
INFO:conda_build.build:Packaging daal
INFO conda_build.build:build(2291): Packaging daal
No files or script found for output daal
WARNING:conda_build.build:No files or script found for output daal
WARNING conda_build.build:bundle_conda(1630): No files or script found for output daal
number of files: 0
Fixing permissions
Packaged license file/s.
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.00 seconds
Packaging daal-include
INFO:conda_build.build:Packaging daal-include
INFO conda_build.build:build(2291): Packaging daal-include
No files or script found for output daal-include
WARNING:conda_build.build:No files or script found for output daal-include
WARNING conda_build.build:bundle_conda(1630): No files or script found for output daal-include
number of files: 0
Fixing permissions
Packaged license file/s.
```
I'm not sure how it should be

**Comment by antkneed** [comment]
> Are logs correct for `daal` and `daal-include` - **0 files**?:

All `daal` packages are essentially metapackages that point to their respective `dal` ones. This was done to preserve backwards compatibility when the package name went from `daal` -> `dal`

**Review by skupr-anaconda — APPROVED** [review]

**Pull request merged**
